### ISSUE TITLE
"Root Element is missing" exception in Transaction.ReadXml

### ISSUE THREAD

**Issue by bnoyle** [recurly/recurly-client-net#51] opened 2014-09-30 16:47 UTC
Attempting to create a transaction via Transaction.Create() returns a Root Element is missing exception in the Transaction object.

Response appears to be empty and transaction is not reflected in Recurly.

**Comment by chvrsri** [comment] 2015-05-25 12:19
Even im facing this issue. When ever i initiate a new request using transaction.Create() im receiving this issue. Please respond with a solution.

**Comment by cbarton** [comment] 2015-05-28 19:03
Sorry for leaving this open so long @chvrsri @bnoyle, can you provide me with some more details into your request (sample code, client version)? I am having a hard time reproducing this error on the current SDK version.

**Comment by chvrsri** [comment] 2015-05-29 04:09
Hi Cbarton,

The amount of the transaction lies in a textbox so the format of that value will be in String. So i have converted the value from String to Int since the Transaction API accepts on INT type Amount only.

Below is the screen shot on exactly where the issue is reproduced. Additionally without any conversion if i'm directly passing an INT type variable then every thing seems to working fine. I have this "ROOT ELEMENT IS MISSING" issue only when we are converting the value into an INT type.

![image](https://cloud.githubusercontent.com/assets/12595940/7876250/50e2794e-05e6-11e5-9f9f-8ad1b15c5cfc.png)

**Comment by cbarton** [comment] 2015-05-30 00:16
What version of the SDK are you using? What is the value for `Val` in your code example? I have tried the converting a number, converting an invalid number, using a normal integer, invalid credit cards, etc and all seem to come back with the proper messages.

**Comment by chvrsri** [comment] 2015-06-01 05:22
I'm Using VS2010 as my SDK. 

These are the steps of making my Val into the transaction API.

For Example:
Initially the Value of Val is a string and then converting the same value into an integer and accessing the same.

![val issue](https://cloud.githubusercontent.com/assets/12595940/7906655/566b5bd4-084c-11e5-9972-bc2b8ad639f8.png)

**Comment by cbarton** [comment] 2015-06-01 21:35
Alright, I have tracked down what is happening here. I can only reproduce this issue when the transaction amount is very small (< 3 cents). This is because when an amount is that small, we do not try and process a transaction, we mark the invoice as paid with no transactions. This results in that API call returning a `204 No Content` (since there is no transaction) and thusly breaks this client library with the `Root Element is Missing` error (since there is no body in the response).

I will get a patch going and have it released by the end of the week. 

Thank you both for bringing this to our attention.

**Closed** 2015-07-06 17:16 UTC
