### ISSUE TITLE
Error in iFrame???

### ISSUE THREAD

**Issue by AnaCampoVe** [recurly/recurly-client-net#210] opened 2017-01-13 10:49 UTC
Hi Team!!! 

Today we have realized that Credit card fields that you have in Recurly iFrame, and we have inserted in  our webpage, are getting crazy. Tab doesn't work, fields content overlaps... Do you have news about any problem of this kind?? This is a really urgent issues, as our customers can't subscribe to Recurly.

Regards,

Ana Campo

**Comment by bhelx** [comment] 2017-01-13 17:14
Hey @AnaCampoVe 

This is an issue for support and isn't related to this library. It looks like you've already contacted them and the problem is being addressed. I'm going to close this. Let me know if there is anything I can do on the .NET side to help.

**Closed by bhelx** 2017-01-13 17:14 UTC
