### ISSUE TITLE
BalanceInCents is 0 after redeeming

### ISSUE THREAD

**Issue by jjwhite** [recurly/recurly-client-net#261] opened 2017-11-29 16:16 UTC
After I call  `giftCard.Redeem(accountCode)`  The BalanceInCents property is set to 0 even after a successful redemption.  I would expect this to be equal to the balance listed on the gift card details page?

**Comment by bhelx** [comment] 2017-11-30 20:03
@jjwhite The reason is that it's `null` in the xml but the property is not nullable (thus it defaults to 0). I've made PR #263 to more accurately reflect this case.
As for why it's null, I believe the `BalanceInCents` refers to the balance left on the card. After redemption the balance has been applied to the account. If you want to know the amount that was redeemed I think you want to look at `UnitAmountInCents`. I'll need to confirm my reasoning as it does seem like the full balance is listed in the admin like you noted.

**Comment by jjwhite** [comment] 2017-12-11 14:08
@bhelx Is there another way to know if the gift card has been successfully redeemed if the balance is not being updated upon redemption?

**Comment by aaron-suarez** [comment] 2018-09-28 17:53
@jjwhite I don't know if you're still experiencing issues with the BalanceInCents being 0 after redemption. I was not able to reproduce this behavior on the latest version of the API (v2.15)

I checked with the team responsible for gift cards and they confirmed that the best way to check if a gift card has been successfully redeemed is to look at the `RedeemedAt` property. This property will be null when the gift card has not been redeemed, and it will have a DateTime when it has been successfully redeemed.

Prior to #343, there was not an easy way to check if a gift card was redeemed. Once this gets merged, you can check using `giftcard.RedeemedAt == null`.

Here's my example script in case you want to try it out yourself

```C#
            var giftcard = new GiftCard("HL3QDCT8AMRWJ4P9");
            var mightBeNull = giftcard.RedeemedAt == null;
            var surelyNull = giftcard.CanceledAt == null;
            Console.WriteLine("GiftCard Redeemed At == null? " + mightBeNull); // GiftCard Redeemed At == null? True
            giftcard.Redeem("x");
            Console.WriteLine("GiftCard Redeemed At: " + giftcard.RedeemedAt); // GiftCard Redeemed At: 9/28/18 12:39:51 PM
```

I'm going to close this issue once #343 is merged. If you're still experiencing problems, please re-open it and describe the steps to reproduce and we'll get it all straightened out. Thanks 😄

**Closed** 2018-10-03 18:48 UTC
