### ISSUE TITLE
Pager<T>.Count() throws NullReferenceException

### ISSUE THREAD

**Issue by aleevans** [recurly/recurly-client-net#655] opened 2021-09-15 17:55 UTC
**Description**

The method `public int Count();` on the generic pager throws a `NullReferenceException` whenever called. The `Pager<T>` object itself is not null, and I am otherwise able to retrieve data as normal through Recurly. It appears that this specific method is broken and dependent on a variable which is null.

**Steps To Reproduce**

```csharp
var pager = client.ListAccountTransactions(accountCode);
var totalCount = pager.Count(); // throws NullReferenceException even though pager is not null.

// or

var pager = client.ListAccountInvoices(accountCode);
var totalCount = pager.Count(); // throws NullReferenceException even though pager is not null.

// In both cases above, it is still possible to call FetchNextPage() and obtain data.  Count() always throws an exception.
```

**Expected behavior**

The method `public int Count();` on `Pager<T>` should return the total count of `T`, regardless of pagination.

**Environment**

- Recurly 4.8.0
- .NET Framework 4.8
- C# 7.3

**Comment by douglasmiller** [comment] 2021-09-15 22:32
@aleevans, I was able to reproduce your issue locally. Based on your code samples, it looks like you're passing in the account's `Code` into the `List*` operations. These two methods expect the account `Id` to be specified. It is possible to use the account `Code` by prefixing it:

> Account ID or code. For ID no prefix is used e.g. `e28zov4fw0v2`. For code use prefix `code-`, e.g. `code-bob`.

https://developers.recurly.com/api/v2021-02-25/index.html#operation/list_account_transactions

```csharp
var pager = client.ListAccountTransactions($"code-{accountCode}");

# and

var pager = client. ListAccountInvoices($"code-{accountCode}");
```

That said, I agree that the client should handle your scenario such that it returns an appropriate Recurly Error.

**Comment by aleevans** [comment] 2021-09-16 02:36
Thanks for looking into this @douglasmiller .  I actually am passing in the account code the way you have it in your code snippet.  I prefixed the account code with `code-` and assigned the result to a variable called `accountCode`.  I tried what you suggested just to be safe (although there shouldn't be any difference), and I am still getting a `NullReferenceException` thrown by the call to `Count()`.

Do you actually get a value back when you call `Count()`?  Or does it throw an exception for you as well @douglasmiller ?

**Comment by douglasmiller** [comment] 2021-09-16 02:50
I do not have any issues when passing in a valid account `Id` or `code-Code`. I can only trigger the `NullReferenceException` when I use invalid values (thus triggering a 404 for the request). Otherwise I get the correct number of resources returned.

The `Count()` method is ultimately performing a `HEAD` request to the URL and obtaining the value from a response header. 

It's well after hours for me, but I can take another look in the morning

**Comment by douglasmiller** [comment] 2021-09-16 17:54
@aleevans, I threw together a quick console app:

```csharp
using System;

namespace aleevans
{
    class Program
    {
        static void Main(string[] args)
        {
            var apiKey = System.Environment.GetEnvironmentVariable("RECURLY_API_KEY");
            var client = new Recurly.Client(apiKey);

            var accounts = client.ListAccounts();
            // Successfully prints the account count
            Console.WriteLine($"Account Count: {accounts.Count()}");

            var accountCode = System.Environment.GetEnvironmentVariable("RECURLY_ACCOUNT_CODE");
            var pager = client.ListAccountTransactions($"code-{accountCode}");
            // Successfully prints the transaction count
            Console.WriteLine($"Transaction Count: {pager.Count()}");

            var errorPager = client.ListAccountTransactions("unknown-account-id");
            // Throws a System.NullReferenceException
            Console.WriteLine($"Transaction Count: {errorPager.Count()}");

        }
    }
}
```

When I run it, `RECURLY_API_KEY=<my-api-key> RECURLY_ACCOUNT_CODE=<valid-account-code> dotnet run`, I get this output:

```
Account Count: 2196
Transaction Count: 2

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Recurly.BaseClient.HandleResponse(IRestResponse resp)
   at Recurly.BaseClient.MakeRequest[T](Method method, String url, Request body, Dictionary`2 queryParams, RequestOptions options)
   at Recurly.Pager`1.Count()
   at aleevans.Program.Main(String[] args) in /private/tmp/aleevans/Program.cs:line 23
```

Could you try the same?

**Comment by aleevans** [comment] 2021-09-16 18:17
@douglasmiller I will try and run what you posted and report back on the results.  Out of curiosity, is the `NullReferenceException` throwing for you because `errorPager` is null?  For my issue, the pager is not null.  I can successfully get data.  It's just that if I try and call `Count()` the error gets thrown.  Take a look at this snippet:

```CSharp
...
var transactions = new List<Transaction>();
var pager = client.ListAccountTransactions($"code-{accountCode}");
var nextPage = pager.FetchNextPage().Data;

transactions.AddRange(nextPage.Where(x => x.Type == TransactionType.Refund || x.Type == TransactionType.Purchase));

// This condition is never true because I actually get transactions
if (transactions.Count() == 0)
{
   // This will not print
   Console.WriteLine("No transactions on first page");
}

// This will throw a NullReferenceException
var count = pager.Count();
...
```

As you can see, the issue is not that I can't get data or that the pager is null, it is just that the specific `Count()` method throws an exception.  I will try your example to see if my results differ.

**Comment by douglasmiller** [comment] 2021-09-16 21:52
Ah! @aleevans, your call to `FetchNextPage` is causing an issue with the `Pager` and the `Count()` method! You could call the `Count()` method immediately after creating the instance of the `Pager` and it would work without an issue. The returned count will be the same regardless of when you call it.

There is a bug in the private `Clone(Pager<T> pager)` method that causes the `Count()` method to fail once the `Pager` has been used to manually iterate over the API results.

**Comment by aleevans** [comment] 2021-09-16 22:01
@douglasmiller  Thanks for looking into it!  I would like to point out though that I have tried calling `Count()` before fetching the next page, and I also get the same `NullReferenceException`.  However, in both cases, I am still able to obtain data and the pager is not null.  So this following code snippet is also true:

```CSharp
...
var transactions = new List<Transaction>();
var pager = client.ListAccountTransactions($"code-{accountCode}");

// This will throw a NullReferenceException, but if I comment it out, the following will work.
// var count = pager.Count();

var nextPage = pager.FetchNextPage().Data;

transactions.AddRange(nextPage.Where(x => x.Type == TransactionType.Refund || x.Type == TransactionType.Purchase));

// This condition is never true because I actually get transactions
if (transactions.Count() == 0)
{
   // This will not print
   Console.WriteLine("No transactions on first page");
}
...
```

**Comment by douglasmiller** [comment] 2021-09-17 16:55
@aleevans I'm struggling to understand how that is possible. The `Count` method is simply performing a HEAD request to the same URL that `FetchNextPage` is performing a GET request to.

If you have a valid response from the GET then the HEAD should also have a valid response. I would only expect the `NullReferenceException` to trigger if there was an issue encountered while performing the API request.

I've opened https://github.com/recurly/recurly-client-dotnet/pull/658 to address the issue with the `FetchNextPage` method's overwriting of the `Url` property of the `Pager`. Once that's merged and released, would you mind trying again with that updated version?

**Comment by douglasmiller** [comment] 2021-09-17 22:10
@aleevans version [4.9.1 has been released](https://github.com/recurly/recurly-client-dotnet/releases/tag/4.9.1). Would you mind trying that version out to see if it addresses your issues?

**Comment by aleevans** [comment] 2021-09-20 21:03
@douglasmiller Sure thing.  I will test it out either later this evening or tomorrow and report back!

**Comment by aleevans** [comment] 2021-09-20 22:29
@douglasmiller Just installed 4.9.1 and tried out the `Count()` method again.  It appears to be fixed, as the `NullReferenceException` no longer occurs and the correct record count is returned.  This bug can probably be closed.  Thank you!

**Comment by douglasmiller** [comment] 2021-09-20 22:42
Great! I'm glad that worked out for you. Please don't hesitate to report any other issues that you find!

**Closed as completed by douglasmiller** 2021-09-20 22:42 UTC
Labels: bug
