### ISSUE TITLE
Exception on Settings.Initialize

### ISSUE THREAD

**Issue by daniel-camilyo** [recurly/recurly-client-net#242] opened 2017-09-06 21:36 UTC
Hi,

I am using latest nu get package in VS2017

When calling Setting.Initialize, there is an null reference exception  deep inside.
It still works as when calling other method there is no exception related to authentication and we get expected data.

You can see in screenshot below
![recurly-setting-exception](https://user-images.githubusercontent.com/31675296/30135596-1927f372-9364-11e7-8f07-91bdf0146e0b.png)

Regards

Daniel

**Comment by bhelx** [comment] 2017-09-06 22:23
@daniel-camilyo Thanks for reporting and thanks for the example!

Is there a reason you are using this class directly and not config files? Wondering if this is related to #160

**Comment by daniel-camilyo** [comment] 2017-09-06 22:44
Yes it seems related!!!.

There a few reason why it is easier for us to connect thru code instead of config:
- the need to switch between Recurly account depending on context (this does not resolve it completely as it is a global static class.
 - we implemented our own wrapper as a dll, and its i used on several project for the same Recurly account - easier to centralize the configuration

Thx

**Comment by bhelx** [comment] 2017-09-06 23:17
@daniel-camilyo Have you tried the solution worked out in #162 ?

**Comment by daniel-camilyo** [comment] 2017-09-06 23:27
Well i did implemented #162 that is where i get my exception.

However digging there i found #189 who give idea to workaround the singletin issue

**Comment by bhelx** [comment] 2017-09-06 23:30
Sorry for the confusion, I should update the README to be a little more clear on how to do this. Were you able to get it to work?

**Comment by daniel-camilyo** [comment] 2017-09-06 23:40
Again it works, from start, - i mean there is null exception inside Initialize - but it is still working.
I just thought it was worth mentioning

**Comment by 1TheMuffinMan** [comment] 2017-09-06 23:55
@daniel-camilyo You said it was working so this probably won't be the issue, but I notice your first variable is called `privateKey` which I'm assuming is actually your API key, and not the Recurly JS private key?

The `Initialize` method excepted arguments in this order:

`public static void Initialize(string apiKey, string subdomain, string privateKey = "", int pageSize = 200)`

**Comment by bhelx** [comment] 2017-09-07 00:10
@daniel-camilyo I guess I misunderstood the part where you said it was still working. Are you just catching and ignoring the exception?

We can try to reproduce this.

@1TheMuffinMan I'd assume it's the right key considering he is actually getting data back.

**Comment by daniel-camilyo** [comment] 2017-09-07 00:16
I am using
[cid:image001.png@01D32787.B849AA20]

It is call in your bac end private api key, so I called it effectively private in  my code

**Comment by bhelx** [comment] 2017-09-07 00:25
Okay, I've tried a few different ways to reproduce but cannot. Here is my code:

```csharp
Recurly.Configuration.SettingsManager.Initialize("<myapikey>", "<mysubdomain>");
var accountCode = "myaccount";
var account = Accounts.Get(accountCode);
Console.WriteLine(account);
```

I have no settings in my `App.config`:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <startup> 
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
  </startup>
</configuration>
```

@1TheMuffinMan Are you able to reproduce?

**Comment by 1TheMuffinMan** [comment] 2017-09-07 00:38
@bhelx No I am not able to reproduce it using that code.

@daniel-camilyo Are you able to jump on a screen share so that I can see where the null reference exception is coming from?

**Comment by bhelx** [comment] 2017-09-07 00:39
@daniel-camilyo is this only happening in a multithreaded environment? I assume you have two recurly accounts and are trying to call both from the same application.

**Comment by aaron-suarez** [comment] 2018-10-15 18:39
Closing this because we cannot reproduce. Feel free to re-open if you can provide some example code that reliably reproduces the issue.

**Closed by aaron-suarez** 2018-10-15 18:39 UTC
Labels: bug?
