### ISSUE TITLE
Add-on Clear and Add-on Remove is not working

### ISSUE THREAD

**Issue by dragankae** [recurly/recurly-client-net#62] opened 2014-12-22 16:02 UTC
Add-on clear and add-on remove is not working. The code below used from the documentation
https://docs.recurly.com/api/subscriptions/subscription-add-ons
is not changing the add-ons of the subscriptions....

var subscription = Subscriptions.Get("2bc2a33060c103d2f0c0b5430b94d2b2");

// remove an add-on
subscription.AddOns.RemoveAt(0);

// remove all add-ons
subscription.AddOns.Clear();

// call for an update
subscription.ChangeSubscription(Subscription.ChangeTimeframe.Now);

**Comment by cgerrior** [comment] 2015-01-06 21:53
Hi, 

I've identified the cause of these failures. We'll close this issue when it's resolved.

Thanks,

Charlie (Sales Engineer @ Recurly)

**Comment by Shawn-TOS** [comment] 2015-01-16 17:43
Just checking in to see if your teams have made any progress on this issue?

**Comment by cbarton** [comment] 2015-01-16 17:45
We have it on track to be in the new release of the client library next week. 

Thank you for your patients with this issue.

**Comment by Shawn-TOS** [comment] 2015-01-16 17:46
That's great news! Thanks for the update! :)

**Comment by TOS-GitHub** [comment] 2015-01-26 15:36
Is there an ETA yet? It's been a few weeks now and it would be beneficial to know when this may or may not be resolved. We just need to know if this is a blocker or not so that we can proceed with our own processes.

**Comment by MuffinMan10110** [comment] 2015-01-26 16:11
FYI I'm working on a Recurly client library of my own that you might be
interested in checking out in the future when it's finished.
https://github.com/MuffinMan10110/recurly

Why would I do this?

   - So that I can fix bugs fast
   - There are existing unit tests in the official library that pass that
   are actually not correct
   - As neat as it is, the architecture makes it very difficult to hide it
   behind a service layer and use something like AutoMapper to map between
   Recurly objects and publicly exposed objects.
   - Most objects have an Async variant

**Comment by austinheap** [comment] 2015-01-27 00:56
This should be fixed now. Please let us know if you encounter further issues.

**Closed** 2015-01-27 00:55 UTC

**Comment by Shawn-TOS** [comment] 2015-01-27 01:09
Thanks guys! Much appreciated!

Thanks,

Shawn Ivie
Support Manager
www.theoldstate.com
