### ISSUE TITLE
The price is not changed on a subscription when the subscription plan is changed

### ISSUE THREAD

**Issue by dragankae** [recurly/recurly-client-net#70] opened 2015-01-27 15:23 UTC
When i update subscription plan on a subscription, the price of the subscription and the addons are not updated to the price of the new plan and new plan addons. I can see that the plan is changed on recurly but not the prices..

This happens using the .NET library.

**Comment by austinheap** [comment] 2015-01-27 22:07
@dragankae Thanks for reporting this. We're looking into it internally.

**Comment by dragankae** [comment] 2015-02-05 13:25
Hello, can you update me about the progress of this issue.
Thanks

**Comment by dragankae** [comment] 2015-02-27 13:54
Let me explain the problem again:

1) I have 2 Plans
PlanA 10$
PlanB 20$

2) My subscription has PlanA 10$
- if i change the plan of the subscription to PlanB through the API the price is still 10$ and the addon prices are not updated according the new plan
- if i change the plan of the subscription to PlanB through user interface the price is correctly updated to 20$ and to all of the addons

3) This is in recurly API documentation https://docs.recurly.com/api/subscriptions/upgrade-downgrade
Plan Code, Quantity, and Unit Amount

Values not specified will be not be changed.
If the subscription plan changes, the unit amount will default to the new plan's unit amount. Of course, you are welcome to override the plan's unit amount by specifying it in the change request.

**Comment by austinheap** [comment] 2015-03-03 19:25
Hi @dragankae, can you provide us with sample code to reproduce the issue?

**Comment by austinheap** [comment] 2015-03-03 19:31
Hi @dragankae, can you please provide some code to reproduce the behavior you're seeing? Thanks.

**Comment by dragankae** [comment] 2015-03-28 16:48
This is what i do:

var activeRecurlySubscription = Recurly.Subscriptions.Get(SubscriptionID);
subscription.Plan =  Recurly.Plans.Get(newPlanCode);; // Set the new plan
subscription.ChangeSubscription(Recurly.Subscription.ChangeTimeframe.Now);

**Comment by whiteotter** [comment] 2015-06-12 01:28
The subscription update api call is somehow including a custom `unit_amount_in_cents`, so the process doesn't default to the plan's value. Because the custom value is the amount of the previous subscription, the amount appears to have never changed.

**Comment by MuffinMan10110** [comment] 2015-06-12 02:32
I'm very confused on what you're trying to explain.

A plan is a template. A subscription is created from that template. Before you save the subscription you can override the defaults that were specified in the template (unit price being one). 

If you then change the template it would not change any of the subscriptions that were created previously. 

If template price is $5.00
You then create a subscription using the template defaults. 
You then change template price to $6.00
You then get previously created subscription and observe the price is $5.00
You then update subscription without changing anything and observe price is $5.00

I'm not sure where the confusion lies in that logic.

**Comment by BrainTrainDev** [comment] 2015-06-15 15:00
It looks like this issue is being caused because assigning a new Plan to a Subscription does not propagate the UnitAmountInCents from the Plan to the Subscription, and ChangeSubscription() submits the Subscription price, not the Plan price.  It can be worked around like so:

    var activeRecurlySubscription = Recurly.Subscriptions.Get(SubscriptionID);
    subscription.Plan = Recurly.Plans.Get(newPlanCode);; // Set the new plan
    subscription.UnitAmountInCents = subscription.Plan.UnitAmountInCents(subscription.Currency);
    subscription.ChangeSubscription(Recurly.Subscription.ChangeTimeframe.Now);

**Comment by MuffinMan10110** [comment] 2015-09-15 17:48
Can we close this? It appears that there was confusion in how the system worked and not an actual bug. If you see my comment above I detail why this is not a concern of the client library.

**Comment by bhelx** [comment] 2015-09-15 17:50
@MuffinMan10110 yes, good point. 

@dragankae feel free to re-open discussion

**Closed by bhelx** 2015-09-15 17:50 UTC

**Comment by BrainTrainDev** [comment] 2015-09-15 20:25
Maybe I should've reported a different bug, but in my test scenarios, no "template" prices are ever changed.  Here's my test scenario:
Assume PlanA @ 149$, PlanB @ 1000$
1) Create new account
2) Create subscription using the new account & PlanA
3) Change subscription to PlanB 
If I do this via the web interface, I would see that the customer is charged the correct, 1000$ rate, but when I go through the same steps with the API, the customer is only charged 149$.
My workaround, above, feels much more like a kludge than an intended pattern.  If you'd like a complete, in-code illustration of the issue, I've got one of those from my original exploration.  
As I did find that workaround, it's no longer a critical issue for us.  I'm just putting in my two cents.

**Comment by MuffinMan10110** [comment] 2015-09-15 21:00
@BrainTrainDev I think the confusion lies in the fact that the Recurly Admin UI is doing one step automatically for you that you might not realize. When you choose a new plan from the drop down when editing your subscription the UI is automatically populating the price field with the new plans price and you can choose to continue with it or override it. This action is equivalent to you setting your subscription objects price to the new plans price when settings the new plan.

**Comment by BrainTrainDev** [comment] 2015-09-15 22:25
Thanks, I think I understand the design now.
