### ISSUE TITLE
Requested value 'Processing' was not found.

### ISSUE THREAD

**Issue by NPSF3000** [recurly/recurly-client-net#211] opened 2017-01-19 16:42 UTC
We're using this lovely library to process our payments, but occasionally it's throwing an exception when returning the list of Invoices.  We suspect this is because the invoice state is 'Processing' and the library doesn't understand than status.

This bug is quite urgent, as it's breaking live functionality for paying customers.

Thanks!

System.ArgumentException: Requested value 'Processing' was not found.
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at Recurly.StringExtensions.ParseAsEnum[T](String source) in C:\Users\ben\Documents\GitHubVisualStudio\recurly-client-net\Library\Extensions\StringExtensions.cs:line 54
   at Recurly.Invoice.ReadXml(XmlTextReader reader) in C:\Users\ben\Documents\GitHubVisualStudio\recurly-client-net\Library\Invoice.cs:line 261
   at Recurly.InvoiceList.ReadXml(XmlTextReader reader) in C:\Users\ben\Documents\GitHubVisualStudio\recurly-client-net\Library\List\InvoiceList.cs:line 31
   at Recurly.Client.ReadWebResponse(HttpWebResponse response, ReadXmlDelegate readXmlDelegate, ReadXmlListDelegate readXmlListDelegate, ReadResponseDelegate responseDelegate) in C:\Users\ben\Documents\GitHubVisualStudio\recurly-client-net\Library\Client.cs:line 378
   at Recurly.Client.PerformRequest(HttpRequestMethod method, String urlPath, WriteXmlDelegate writeXmlDelegate, ReadXmlDelegate readXmlDelegate, ReadXmlListDelegate readXmlListDelegate, ReadResponseDelegate reseponseDelegate) in C:\Users\ben\Documents\GitHubVisualStudio\recurly-client-net\Library\Client.cs:line 169
   at Recurly.Client.PerformRequest(HttpRequestMethod method, String urlPath, ReadXmlListDelegate readXmlListDelegate) in C:\Users\ben\Documents\GitHubVisualStudio\recurly-client-net\Library\Client.cs:line 120
   at Recurly.RecurlyList`1.GetItems() in C:\Users\ben\Documents\GitHubVisualStudio\recurly-client-net\Library\List\RecurlyList.cs:line 89
   at Recurly.Invoices.List(String accountCode) in C:\Users\ben\Documents\GitHubVisualStudio\recurly-client-net\Library\Invoice.cs:line 421

**Comment by 1TheMuffinMan** [comment] 2017-01-19 16:55
Thank you for reporting.

@bhelx Do you have any reservations with adding this state to the invoice enum? I ask because it may be a situation where you can only query for a subset of the available states. For instance, you couldn't query for invoices in `Processing` state, but invoices in that state would be returned if you queried for `All` invoices.

**Comment by bhelx** [comment] 2017-01-19 17:16
@NPSF3000 @1TheMuffinMan Yes, I think we should add it. This is a newer state that applies only to asynchronous invoices (ACH invoices)

**Comment by bhelx** [comment] 2017-01-19 19:12
@1TheMuffinMan sorry to answer your question more directly, I don't have any reservations about that.

**Comment by 1TheMuffinMan** [comment] 2017-01-20 01:53
@bhelx I'm working on the unit test for this and when I try to create ACH billing info using the sample here https://dev.recurly.com/docs/create-an-accounts-billing-info-bank-account I get `account.routing_number invalid`. Is there a test number similar to credit cards (4111111111..) that I should use here or does the account we're running the tests against need to be provisioned for ACH? I notice there aren't existing tests for that feature.

**Comment by bhelx** [comment] 2017-01-20 04:29
@1TheMuffinMan yes, assuming you are using the test gateway, you can find test numbers here:
https://docs.recurly.com/docs/test

You'll probably want to use `Routing Number: 123456780` and `Account Number: 111111111`

**Comment by 1TheMuffinMan** [comment] 2017-01-20 17:10
@bhelx Thank you for the link!

@NPSF3000 Just want to let you know that I submitted a pull request for this fix and hopefully we can get it merged soon. Thanks for your patience.

**Comment by bhelx** [comment] 2017-01-20 17:20
Thanks @1TheMuffinMan 
I'll get it merged and do a patch release today.

**Closed** 2017-01-20 17:28 UTC

**Comment by bhelx** [comment] 2017-01-20 17:50
Okay, I've released this as https://github.com/recurly/recurly-client-net/releases/tag/1.4.8

Nuget: https://www.nuget.org/packages/recurly-api-client/1.4.8

**Comment by NPSF3000** [comment] 2017-01-20 20:37
@bhelx and @1TheMuffinMan.

Thank you so much for your quick and prompt resolution in this manner.  We'll update our library and do regression testing shortly.

**Comment by 1TheMuffinMan** [comment] 2017-01-20 20:47
@NPSF3000 You're welcome! Please let us know if you're still having issues or encounter anything else.

**Comment by NPSF3000** [comment] 2017-01-20 20:56
@1TheMuffinMan @bhelx Can you please just take a quick look at the latest nuget package?  When I updated VS complained it can't find the dll.

Under 'packages\recurly-api-client.1.4.8\lib\net35' I have a 'Recurly.dll - Shortcut' instead of a dll.

**Comment by bhelx** [comment] 2017-01-20 22:11
@NPSF3000 seems like the release copied a shortcut of the dll. I've released 1.4.9 to fix it. Could you let me know if this works out?

**Comment by NPSF3000** [comment] 2017-01-24 15:46
@bhelx seems to be working now, much appreciated.

**Comment by NPSF3000** [comment] 2017-01-31 17:06
@bhelx  @1TheMuffinMan Sorry to be a nuisance, but we're seeing this problem again in a new production push.  Still on 1.4.9.  Could you maybe take a quick look at the following stacktrace to rule out the driver?

```
System.ArgumentException: Requested value 'Processing' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at Recurly.StringExtensions.ParseAsEnum[T](String source) in C:\Users\ben\Documents\GitHubVisualStudio\recurly-client-net\Library\Extensions\StringExtensions.cs:line 54
   at Recurly.Transaction.ReadXml(XmlTextReader reader) in C:\Users\ben\Documents\GitHubVisualStudio\recurly-client-net\Library\Transaction.cs:line 222
   at Recurly.TransactionList.ReadXml(XmlTextReader reader) in C:\Users\ben\Documents\GitHubVisualStudio\recurly-client-net\Library\List\TransactionList.cs:line 49
   at Recurly.Invoice.ReadXml(XmlTextReader reader) in C:\Users\ben\Documents\GitHubVisualStudio\recurly-client-net\Library\Invoice.cs:line 359
   at Recurly.InvoiceList.ReadXml(XmlTextReader reader) in C:\Users\ben\Documents\GitHubVisualStudio\recurly-client-net\Library\List\InvoiceList.cs:line 31
   at Recurly.Client.ReadWebResponse(HttpWebResponse response, ReadXmlDelegate readXmlDelegate, ReadXmlListDelegate readXmlListDelegate, ReadResponseDelegate responseDelegate) in C:\Users\ben\Documents\GitHubVisualStudio\recurly-client-net\Library\Client.cs:line 378
   at Recurly.Client.PerformRequest(HttpRequestMethod method, String urlPath, WriteXmlDelegate writeXmlDelegate, ReadXmlDelegate readXmlDelegate, ReadXmlListDelegate readXmlListDelegate, ReadResponseDelegate reseponseDelegate) in C:\Users\ben\Documents\GitHubVisualStudio\recurly-client-net\Library\Client.cs:line 169
   at Recurly.Client.PerformRequest(HttpRequestMethod method, String urlPath, ReadXmlListDelegate readXmlListDelegate) in C:\Users\ben\Documents\GitHubVisualStudio\recurly-client-net\Library\Client.cs:line 120
   at Recurly.RecurlyList`1.GetItems() in C:\Users\ben\Documents\GitHubVisualStudio\recurly-client-net\Library\List\RecurlyList.cs:line 89
   at Recurly.Invoices.List(String accountCode) in C:\Users\ben\Documents\GitHubVisualStudio\recurly-client-net\Library\Invoice.cs:line 422
```

**Comment by 1TheMuffinMan** [comment] 2017-01-31 17:11
@NPSF3000 Looks like while invoices enum has the processing state, one of the transaction enums (there's 2) needs that state as well. It's not clear which one from the stack trace. Tonight I will reproduce this, fix it and add a new unit test.

Thanks for reporting.

**Comment by bhelx** [comment] 2017-01-31 17:16
@1TheMuffinMan It might be transaction. I'll send a PR today to catch this and see if there are some other values missing

**Comment by bhelx** [comment] 2017-01-31 17:22
@NPSF3000 Standby for another PR. I'll be pushing out another fix today.

**Comment by bhelx** [comment] 2017-01-31 19:34
@1TheMuffinMan @NPSF3000 I went ahead and made sure all the enum values I could find were up to date: https://github.com/recurly/recurly-client-net/pull/215
