### ISSUE TITLE
Subscription Postpone Date/Time is + 7hrs off of API input (local time)

### ISSUE THREAD

**Issue by bhelx** [recurly/recurly-client-net#198] opened 2016-12-13 19:23 UTC
Subscription.Postpone seems to be off when passing a local datetime.

Description:

C# Subscription Postpone, does not set the localized time in the app. Enter a local local postpone time/date, and the app shows the time as +7 hours ahead of UTC.

```csharp
using System;
using Recurly;
// demos the input of 1:00 pm local time, while the app then shows 8:00pm local time, 7 hour difference.
namespace SubscriptionPostpone     
{
    
    class Program
    {
        static void Main(string[] args)
        {
            var subscription = Subscriptions.Get("3a2f2209bcfd05b5fb9bc2459a9ddaaf");
            subscription.Postpone(new DateTime(2016,12,14,13,0,0,
                DateTimeKind.Local)
                );
        }
}
```

\cc @elliottbernstein

**Comment by MuffinMan10110** [comment] 2016-12-13 23:45
@bhelx To confirm, you're specifying a postpone date, however when you view the modified subscription  the `CurrentPeriodEndsAt` has a 7 hour difference?

**Comment by bhelx** [comment] 2016-12-14 17:34
@MuffinMan10110 I'm not 100% sure I'm going to look into this today or tomorrow. I got this report from our support team. I suppose the problem is that this is sending over the local time and our servers are treating it like UTC:

https://github.com/recurly/recurly-client-net/blob/master/Library/Subscription.cs#L463

**Comment by MuffinMan10110** [comment] 2016-12-14 18:09
I'm willing to bet that sending it in local time is the issue. Generally in API design you just work with dates in a UTC manner. In our case we need to be more descriptive in what format we expect, UTC, local or both and if we do accept both we check if it's local time and convert it to UTC before sending to the server.

Now the issue arises of when you get the subscription from the server, since we'd be getting UTC dates we'd have to convert them to local, however now the .net client is making assumptions about what time zone the user wants those dates in.

I think the easiest way is to be implicit and only handle UTC dates. All methods and objects assume UTC and the developer can convert them to whatever time zone they want.

**Comment by SuperStromboli** [comment] 2017-01-11 20:27
I believe this issue originated with me via support.

I had created a new DateTime at 12:00:00 to ensure the subscription would renew at midnight.  After calling Postpone, the sub's CurrentPeriodEndsAt ended up being +7 hrs.  The value I passed in was most likely not UTC, so that is a workaround I could try.  I think what @1TheMuffinMan said about passing UTC is perfectly reasonable.

**Comment by 1TheMuffinMan** [comment] 2017-01-23 20:58
@bhelx After speaking with you here's the lowdown on how the `DateTimeKind` works. By default the kind will be `Unspecified` and you can choose to set it to two other types which are `Local` and `Utc`. Based on our conversation we could do the following:

1. If a DateTime being passed into a method is `DateKindType.Unspecified` we throw an exception saying it needs to be specified
2. If the `DateTimeKind` is `Local` the library can automatically convert it to UTC before sending it to the API
3. If the `DateTimeKind` is `Utc` then no changes would be required internally 
4. Additionally, when the client library receives data from the API it should set the `DateTimeKind` to Utc instead of leaving it unspecified.

Other thoughts:

- This change would require everyone to go through their code and specify a `Kind` for their datetimes. This will most defintely be a pain. What I suggest is that we add a configuration variable to the client library called `TreatUnspecifiedDateTimeAs` and allow people to specify the default in just one place.

**Comment by jjwhite** [comment] 2017-01-23 21:22
I'm having a similar problem with the Postpone() method.  I'm passing a valid UTC date/time that is the current datetime.  I receive back an "invalid data" error.  I've even tried adding up to 2 hours to the time being passed in and I'm still getting the "invalid data" error.  The only time the call worked was when I accidentally called ToUniversalTime() on a date that was already UTC which added an additional 5 hours to the time.  It almost seems like even though I'm passing in a datetime that occurs in the future, Recurly is seeing it as being in the past and thrown an exception.

**Comment by 1TheMuffinMan** [comment] 2017-01-23 22:06
@jjwhite I'll get more acquainted with this date time issue this week. The documentation doesn't specify any specific constraints about the date (not even if it can be in the past) so it will be interesting if it turns out there are some constraints such as not being able to set a date too close to the last one, etc.

**Comment by 1TheMuffinMan** [comment] 2017-01-24 04:48
@jjwhite I ran the Postpone unit test with a bunch of different data and wasn't receiving an error when trying to postpone using near values such as 2 hours from now. 

To keep this thread on a single topic (using non UTC dates) do you mind opening up a separate issue regarding the Postpone method? If you do choose to it would also be helpful if you could include a snippet of code you're using and possibly the xml that is being sent to the server. With the proper data to reproduce we can work on getting a fix out fast if there is a bug.

**Comment by jjwhite** [comment] 2017-01-24 16:21
Added a new issue: #214

**Comment by 1TheMuffinMan** [comment] 2017-02-13 20:27
I've added a response to issue #214 and closing this issue.

**Closed by 1TheMuffinMan** 2017-02-13 20:27 UTC
