### ISSUE TITLE
Error creating a subscription via API with Add-Ons

### ISSUE THREAD

**Issue by jvalladolid** [recurly/recurly-client-net#163] opened 2016-09-14 12:03 UTC
I'm trying to create a subscription using the API provided by Recurly. The plan has an add-on that is usage based. When I create the subscription without any AddOn, the request works perfectly and the subscription is created. But if I try to create it with the AddOn that exists in the plan, the request fails. The error raised is "Recurly.ValidationException: The information being saved is not valid"

This is the XML that I send when I create the subscription without any AddOn; all ok
`<?xml version="1.0" encoding="utf-8"?> <subscription>
	<plan_code>PLAN_CODE</plan_code>
	<currency>GBP</currency>
	<subscription_add_ons />
	<customer_notes />
	<terms_and_conditions />
	<vat_reverse_charge_notes />
	<quantity>1</quantity>
	<account>
		<account_code>CODE</account_code>
		<email>XXXXXX@XXXXX.XXX</email>
		<tax_exempt>false</tax_exempt>
		<address>
			<address1 />
			<address2 />
			<city />
			<state />
			<zip />
			<country />
			<phone />
		</address>
	</account>
</subscription>`

And this is the XML that I send when I want to create the subscription with an AddOn already existing in the Plan. The request fails because the information being saved is not valid
`<?xml version="1.0" encoding="utf-8"?> <subscription>
	<plan_code>PLAN_CODE</plan_code>
	<currency>GBP</currency>
	<subscription_add_ons>
		<subscription_add_on>
			<add_on_code>TransactionAmountAddOn</add_on_code>
			<quantity>1</quantity>
			<unit_amount_in_cents>0</unit_amount_in_cents>
		</subscription_add_on>
	</subscription_add_ons>
	<customer_notes />
	<terms_and_conditions />
	<vat_reverse_charge_notes />
	<quantity>1</quantity>
	<account>
		<account_code>CODE</account_code>
		<email>XXXXXX@XXXXX.XXX</email>
		<tax_exempt>false</tax_exempt>
		<address>
			<address1 />
			<address2 />
			<city />
			<state />
			<zip />
			<country />
			<phone />
		</address>
	</account>
</subscription>`

Checking with the documentation and some examples, the XML looks good.
As the AddOn created in the plan is a usave based AddOn, I also tried to remove the unit_amount_in_cents tag from the XML, but same error is reported.

Any ideas about what's happening?

Thanks in advance

**Comment by bhelx** [comment] 2016-09-14 22:38
@jvalladolid Thanks for having such a thorough description. Do you have an idea of what the returned xml response looks like or what the specific validation errors look like? Usually the validation errors refer you to the xml key which is invalid.

**Comment by bhelx** [comment] 2016-09-14 22:39
Also, I'll try to reproduce this.

**Comment by bhelx** [comment] 2016-09-14 22:45
@jvalladolid I can't seem to reproduce. If there is any sample code you can give me to reproduce that would be great. Can you also state which version of the library you are on?

**Comment by jvalladolid** [comment] 2016-09-15 08:21
@bhelx Thanks for the quick answer. Yeah, yesterday I was researching a bit more and I realized that the problem was when reading the response, really. I forgot to mention that I'm using the .NET client to do the requests. I'm extending it to include the support for the UsageRecord endpoint.

**Comment by bhelx** [comment] 2016-09-15 16:36
@jvalladolid just so you know, i have a WIP PR coming down the pipe for usage based billing that i hope to get out this week.

https://github.com/recurly/recurly-client-net/pull/165

Any comments you have there would be helpful.

**Comment by jvalladolid** [comment] 2016-09-16 07:39
@bhelx I have already left a single comment about the UsageTimestamp, that I think it should be mandatory.
On the other hand, I have been creating subscriptions with AddOns and during the tests, I identified some problems with the XML that is generated now. The <unit_amount_in_cents> tag is always included, but it's not required when the AddOn type is "usage". I did some changes in the SubscriptionAddOn and SubscriptionsAddOnList classes for that. So, once you complete your WIP PR with the usage based billing support, let me know please, to merge into my branch. I'll remove my implementation for the usage based billing (cause it's exactly the same as your changes), but I'll keep the changes done to exclude the unit_amount_in cents tag when usage.

**Comment by bhelx** [comment] 2016-09-19 21:18
@jvalladolid it should be out now. Any PRs you wish to have reviewed I'd be happy to get them merged and released. Thanks a lot for your help!

**Comment by bhelx** [comment] 2016-09-30 23:23
Closing unless this has more discussion needed.

**Closed by bhelx** 2016-09-30 23:23 UTC
