### ISSUE TITLE
Add support for ASP.NET Core

### ISSUE THREAD

**Issue by HelgeSverre** [recurly/recurly-client-net#152] opened 2016-06-06 16:12 UTC
Since the way configuration files are changed in ASP.NET 5/Core, i would like to see this implemented in the recurly client, or the option to create an instance of the client with parameters for configuration, as per now, afaik, the recurly .NET client does not work in ASP.NET MVC 6 projects.

However if anyone knows how to get it working, i'd be glad :)

**Comment by MuffinMan10110** [comment] 2016-06-06 16:22
This is a good idea that I don't think anyone has thought about yet. I think some research will need to be done to determine how this change affects backwards compatibility. If you have an idea and can help contribute a pull request would be welcomed.

In the meantime I have addressed how to update the configuration settings at runtime in a previous question https://github.com/recurly/recurly-client-net/issues/148#issuecomment-214923280

Let me know if that works for you.

**Comment by CodingGorilla** [comment] 2016-08-30 19:52
Since recurly does not target one of the .NETStandard versions, it cannot be added to a .NET Core project.  Has anyone found a simple work-around for this?

**Comment by MuffinMan10110** [comment] 2016-08-30 22:53
I don't think there is a simple workaround for it because as you pointed out all of the code is targeted at the standard .NET Framework. The library would need to be ported to .NET Core. If you're up for porting it I'm sure it would be welcomed.

**Comment by kkbxxi** [comment] 2016-09-05 01:26
I have just ported it and also made most of underlying async. Not tested thoroughly yet, but hope to share it to the public withing a week or so.

It is heavily based on code from this repo, and I tried to leave as many of interfaces the same as possible.

**Comment by MuffinMan10110** [comment] 2016-09-05 01:51
@kkbxxi That's awesome news. Thanks for taking that on. It will be interesting to see how we can keep all of the client libraries in sync as currently there is a .NET 3.5 and 4.5 version. This would be the third library. @bhelx any thoughts?

**Comment by kkbxxi** [comment] 2016-09-05 07:24
That's my concern as well. Due to async-related changes, the API is not the same, so I am not sure if it's fair to package old 4.5 and new .NET Core code together. And, I'm not that good with building nuget packages too. 

BTW: I might be missing something, but it says that 3.5 has gone away with 1.3.0, hasn't it?

**Comment by 4nonym0us** [comment] 2017-09-10 11:06
I see that the issue is old a bit, but .NET Core support is getting more important (especially when .NET Core 2.0 was already released and platform seems to be much more mature then it used to be a year ago).
I've checked the repo and  It looks like that the only thing that need to be changed to support netcoreapp2.0 targeting framework is upgrading setting management. There will be no more possibility to read `web.config` or `app.config` so I've cloned the repo and tested following scenario (all of 3 methods are working fine):
```csharp

        static void Main(string[] args)
        {
            var configuration = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json")
                .Build();

            // Method 1
            SettingsManager.InitializeFromConfigRoot(configuration);

            // Method 2 - s
            SettingsManager.Initialize("123456789", "subdomain.com", "XYZ-optionalPrivateKey", 200);

            // Method 3
            SettingsManager.Initialize(
                configuration["Recurly:ApiKey"],
                configuration["Recurly:Subdomain"],
                configuration["Recurly:PrivateKey"],
                Convert.ToInt32(configuration["Recurly:PageSize"]));
        }
```
While `appsettings.json` should have following structure:
```json
{
  "Recurly": {
    "ApiKey": "1",
    "Subdomain": "2",
    "PrivateKey": "3",
    "PageSize": 50 
  }
}
```
In addition, I would consider adding a new Recurly.AspNetCore extension Nuget-package to support ASP.NET Core directly. The extension should look like the snippet below and it's usage will be similar to the samples above.
```csharp
    public static class RecurlyApplicationBuilderExtensions
    {
        public static IApplicationBuilder UseRecurly(this IApplicationBuilder app, string apiKey, string subdomain, string privateKey = "", int pageSize = 50)
        {
            if (app == null) throw new ArgumentNullException(nameof(app));
            if (apiKey == null) throw new ArgumentNullException(nameof(apiKey));

            SettingsManager.Initialize(apiKey, subdomain, privateKey, pageSize);

            return app;
        }
        public static IApplicationBuilder UseRecurly(this IApplicationBuilder app, IConfigurationRoot configuration)
        {
            if (app == null) throw new ArgumentNullException(nameof(app));
            if (configuration == null) throw new ArgumentNullException(nameof(configuration));

            SettingsManager.InitializeFromConfigRoot(configuration);

            return app;
        }
    }
```
I'd like to ask if recurly devs are considering to port the library themselves or accepting a PR?

**Comment by CodingGorilla** [comment] 2017-11-20 23:32
Seems like this hasn't moved much, but there are two possible implementations for .NET Core?  We are getting ready to port our applications to .NET Core, so I was wondering what the status on this is.

**Comment by bhelx** [comment] 2017-11-20 23:37
We haven't made up our mind just yet. It would be great to have but is an issue of backwards compatibility and priority. I'm expecting .NET Core support in the next major version of the library but that could be next year at earliest (and will likely not be backwards compatible). I'm still open to looking at PRs and continuing the conversation. No one at Recurly is actively working on it at the moment.

**Comment by bhelx** [comment] 2017-11-20 23:38
@4nonym0us I was made to believe it would take more than that to upgrade, however if that is what is holding you back, I'd be happy to merge any PRs you need.

**Comment by CodingGorilla** [comment] 2017-11-21 01:02
@bhelx I really don't think backwards compatibility with the current version is really possible, particularly because .NET Core is primarily async (where feasible) as mentioned @kkbxxi.  My personal opinion is that this is likely the way things _should_ be in the .NET core world and thus warrants a completely separate client (e.g. a `Recurly.NETCore v1.0.0`).  If you don't write one, I will for our own internal uses at least, I'm happy to contribute it though if that's desired.

**Comment by 4nonym0us** [comment] 2017-11-21 14:18
@bhelx As far as I know, there is only one option to support full backward compatibility, which is achieved by developing on .NET Standard and targeting multiple frameworks and using conditional project references (if required) like this
```xml
  <ItemGroup Condition=" '$(TargetFramework)' == 'net461' ">
    <Reference Include="ANY_NET461_REFERENCE" />
    <PackageReference Include="ANY_NET461_PACKAGE" Version="1.0.0.0" />
  </ItemGroup>
```
and using pre-processors to handle the 'platform things'
```csharp
#if NET461
//do net461 things (for example, use old ConfigurationSection API to get the app settings)
#endif
#if NETCOREAPP2_0
//do .net core 2+ things (for example, use new ConfigurationBuilder API to get the app settings)
#endif
```
Building such a project will result in a set of multiple NuGet-packages for every platform you are targeting.
As your project is originally .NET Framework project and relies on it's API, you probably need to target only .NETFramework and .NETStandard (.NET Standard is generic specification. Basically .NET Core is implementation of .NET Standard 'interfaces'), which will save the backward compatibility with older versions of .NET Framework and let developers target your library from .NET Core, Mono, Xamarin, UWP, Windows Phone, etc.
Personally, I would leave the .NET Framework in a past in favor of .NET Standard because it simplifies the development a lot and it's definitely the thing to do sooner or later anyway.
<hr>
The reason I stopped investigating recurly is that some Unit-Tests are failing at current master branch so I decided that even If I port the library to .NET Standard or .NET Core I wouldn't be able to pass the tests, which makes the PR kinda useless.

![image](https://user-images.githubusercontent.com/2701409/33077093-78bd23ee-ced7-11e7-9b3f-a4fb4cf95a19.png)

**Comment by NPSF3000** [comment] 2018-03-01 17:22
Any update on this?  It's 2018 and .net core is far more mature, supported... and starting to become a business necessity for us.

**Comment by NPSF3000** [comment] 2018-04-13 19:08
@bhelx any update? 

I'm about to recommend we encapsulate this legacy code in a microservice... which is an expensive solution but might become necessary if .Net Core support is not forthcoming.

@4nonym0us one option would be for recurly to create a RecurlySettings class, we could then use the OptionsManager to DI in an IOptions<RecurlySettings>.  That way as a programmer I don't have my libraries telling me *how* to set up my config files, but it's still pretty painless for the majority case.

**Comment by 4nonym0us** [comment] 2018-04-13 20:46
@NPSF3000 using IOptions would bring ASP.NET Core as a dependency, which isn't the best thing to do for such a client library like recurly.

**Comment by bhelx** [comment] 2018-07-09 20:34
@jamesbar2 I'm happy to take any PRs that can help ease the pain on this library. We'll just need to thoroughly test them.

Everyone: .NET Core support is not currently on our roadmap for this library. We do have plans for a new, less fragile .NET library written from the ground up with .NET core support. If you are interested in this, please email us with the subject "V3 .NET Beta"  achapello@recurly.com, ben@recurly.com

**Comment by sk8main** [comment] 2018-07-12 02:43
It would be really helpful if this library was updated to target .NET Core. For our project this library is the library holding us back from moving to .NET Core. Please, please update

**Comment by drewish** [comment] 2018-07-16 17:20
@sk8main I'd encourage you to drop an email to the addresses listed on https://github.com/recurly/recurly-client-net/issues/152#issuecomment-403611308

**Comment by bhelx** [comment] 2018-09-12 18:08
Hey everyone, we still do not have plans to officially support .NET core with this library, but @aaron-suarez and myself have spent some time getting development of this library to work on macos using mono and these changes have made it possible to use this library from .NET core. Two things are needed:

1. Make sure you are using [this static method](https://github.com/recurly/recurly-client-net/#configuration) to configure the library and not the legacy `web.config` or `app.config`.
2. Follow these directions to compile the library and manually link to the dll: https://github.com/recurly/recurly-client-net/#net-core-and-standard-support

Once again, this is still not officially supported but may offer some people relief until the next major version. I'm going to close this issue for now but please feel free to keep the conversation going or send any pull requests you think may be helpful.

**Closed by bhelx** 2018-09-12 18:08 UTC

**Comment by bhelx** [comment] 2019-05-04 20:30
Everyone: Wanted to drop a follow up in here. The next major version of our API and this library is underway. We've released the new dotnet client as part of our "Early Access" program and it supports dotnet core as well as async calls. If you are interested in trying it out, you can find some information here: https://dev.recurly.com/v2.19/page/recurly-v3-api-early-access
I'd also suggest you email domino@recurly.com and ben@recurly.com to discuss how we can support you.

**Comment by jamesbar2** [comment] 2019-05-07 18:49
@bhelx I asked some of the people who work with your client and this is one of the replies. 
> Interfaces - IRecurlyClient please. At least it's not all statics this time around, so that's good. Also, the new version appears to support .NET Framework 4.7.2 (via .NET Standard 2.0) / .NET Core _only_ by way of their framework targeting, so it might be worth bringing that up so that projects still targeting 4.5 or older can reference the new library.

**Comment by bhelx** [comment] 2019-05-07 18:58
@jamesbar2 That's a good suggestion. The new client does directly expose the Client class right now, but we do have plans for an interface. 

Also, we're in a stage of collecting feedback for any interface / design suggestions we can make before we go out of beta (release 3.0.0). Feel free to reach out to us with any other suggestions and we'll prioritize getting them in before we go GA.

**Comment by BrydenOliver** [comment] 2019-05-08 00:20
@bhelx We have been urgently awaiting this. This is now the only microservice in our solution still stuck on .Net Framework. This is starting to cause serious pain. @PaulPower1 is leading the development effort on our side.
