### ISSUE TITLE
Subscription change issue

### ISSUE THREAD

**Issue by tuhland** [recurly/recurly-client-net#379] opened 2019-03-05 16:58 UTC
There are some dangerous issues with the way the _SubscriptionChange_ object works.

If you take this code, for example: 

                var change = new SubscriptionChange 
                { 
                    TimeFrame = SubscriptionChange.ChangeTimeframe.Now,
                    NetTerms = 30,
                    PoNumber = "12345"
                };

                ChangeSubscription(subscriptionUuid, change);

What you would expect: 

- Net terms and PO number are updated to new values.

What actually happens is:

- **All add-ons are removed from the subscription!**
The addon-list defaults to an empty list, instead of _null_. You can't actually _null_ it, because the property getter (which is called when writing the XML) will just recreate an empty list.
- Net terms and PO number are **not** updated. 
You have to also set the _CollectionMethod_ property, even if it didn't change, because of a check in the _WriteChangeSubscriptionXml_ method.

**Comment by aaron-suarez** [comment] 2019-03-06 16:52
@tuhland Thank you for reporting this. Looking into the issue 👀

**Comment by aaron-suarez** [comment] 2019-03-07 18:50
@tuhland I have confirmed the problems that you describe. I want to point out that it looks like these problems existed before the SubscriptionChange objects were introduced, but I agree that these should be fixed. In the case of subscription add-ons, we should be able to just make it nullable and ensure that the XmlWriter doesn't write a tag unless it contains a value.

As for net terms and PO number, I believe the assumption at the time it was written was that those values can only be changed on a manual invoice. I am unsure whether that is still the case, but either way, client side validation is not something I support, so I'm a fan of removing that check either way. If the API won't allow you to set those values, you'll just have to null them out before sending in a request.

Thanks for bringing this up, I'll get in the fix for this as soon as possible.

**Closed** 2019-03-09 00:27 UTC
Labels: bug
